In [1]:
import numpy as np

In [11]:
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])

In [4]:
print tensor_2d

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
#Um valor em um tensor 2d é identificado pela expressao tensor_2d[row, col], onde, row é a posição da linha e col é
#a posição da coluna

In [13]:
tensor_2d[3][3]

15

In [14]:
#Tensor handling

In [15]:
import tensorflow as tf

In [16]:
#vamos criar 2 arrays de inteiros. Eles representam duas matrizes 3 x 3

In [17]:
matrix1 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)], dtype='int32')

In [18]:
matrix2 = np.array([(1, 1, 1), (1, 1 ,1), (1, 1, 1)], dtype='int32')

In [21]:
print "matrix1 ="
print matrix1

matrix1 =
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [22]:
print "matrix2 ="
print matrix2

matrix2 =
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [23]:
#Para que possamos utilizar essas matrizes em nosso ambiente Tensorflow, elas devem ser transformadas em uma
#estrutura tensor de dados

In [24]:
matrix1 = tf.constant(matrix1)

In [25]:
matrix2 = tf.constant(matrix2)

In [26]:
#Utilizamos o operador constant do tf para realizar a operação de transformação

In [28]:
#As matrizes estão prontas para serem manipuladas com operadores do tensorflow. Neste caso, vamos calcular a multi-
#plicação e a soma das matrizes

In [29]:
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1, matrix2)

In [30]:
#A matriz abaixo será utilizada para calcular a sua determinante

In [31]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype='float32')

In [32]:
print "matrix3 ="
print matrix_3

matrix3 =
[[ 2.  7.  2.]
 [ 1.  4.  2.]
 [ 9.  0.  2.]]


In [33]:
matrix_det = tf.matrix_determinant(matrix_3)

In [34]:
#Agora vamos criar nosso grafo e rodar a session com os tensores e operadores criados

In [36]:
with tf.Session() as sess:
    result1 = sess.run(matrix_product)
    result2 = sess.run(matrix_sum)
    result3 = sess.run(matrix_det)

In [37]:
print "matrix1*matrix2 ="
print result1

matrix1*matrix2 =
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [38]:
print "matrix1 + matrix2 ="
print result2

matrix1 + matrix2 =
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [39]:
print "matrix3 determinant result ="
print result3

matrix3 determinant result =
56.0
